# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EO_Classfication
                                 A QGIS plugin
 This plugin classifies the raster layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-09
        copyright            : (C) 2022 by Xu Qiongjie
        email                : qiongjie.xu@mail.polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EO_Classfication class from file EO_Classfication.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eo_classification import EO_Classfication
    return EO_Classfication(iface)
